### ISSUE TITLE
I don't know what's going on

### ISSUE THREAD

**Issue by ToxicDoc12** [TheCBProject/CodeChickenLib#378] opened 2021-11-18 08:46 UTC
- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16_1.jar)
  ForgelinPlugin (Forgelin-1.8.4_1.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  OTGCorePlugin (OTG-Core.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31_1.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390_1.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 11/18/21 3:45 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 357390856 bytes (340 MB) / 939524096 bytes (896 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=LgjH2m5c8emE66pjdExmgep47BAdKTrCJ7ance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                  | Source                                           | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | mcp                                          | 9.42                     | minecraft.jar                                    | None                                     |
	| LCH   | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCH   | otgcore                                      | 1.12.2-v9.3              | minecraft.jar                                    | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                    | None                                     |
	| LCH   | ctm                                          | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31_1.jar                      | None                                     |
	| LCH   | appliedenergistics2                          | rv6-stable-7             | appliedenergistics2-rv6-stable-7_1.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | architecturecraft                            | @VERSION@                | architecturecraft-1.12-3.98.jar                  | None                                     |
	| LCH   | better_diving                                | 1.5.8                    | BetterDiving-1.12.2-1.5.8_1.jar                  | None                                     |
	| LCH   | bibliocraft                                  | 2.4.5                    | BiblioCraftv2.4.5MC1.12.2.jar                    | None                                     |
	| LCH   | biomesoplenty                                | 7.0.1.2444               | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar    | None                                     |
	| LCH   | openterraingenerator                         | v9.3                     | OpenTerrainGenerator-1.12.2-v9.3.jar             | None                                     |
	| LCH   | bbop                                         | 1.0                      | Biome_Bundle_O_Plenty-1.12.2_v1.0.jar            | None                                     |
	| LCH   | camera                                       | 1.0.10                   | camera-1.0.10_1.jar                              | None                                     |
	| LCH   | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCH   | shadowmc                                     | 3.8.0                    | ShadowMC-1.12-3.8.0_1.jar                        | None                                     |
	| LCH   | clipboard                                    | @VERSION@                | Clipboard-1.12-1.3.0_1.jar                       | None                                     |
	| LCE   | codechickenlib                               | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                                 | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal_1.jar        | None                                     |
	| LC    | cofhcore                                     | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal_1.jar          | None                                     |
	| LC    | cofhworld                                    | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal_1.jar         | None                                     |
	| LC    | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LC    | jei                                          | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                        | None                                     |
	| LC    | twilightforest                               | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar    | None                                     |
	| LC    | tconstruct                                   | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LC    | conarm                                       | 1.2.5.10                 | conarm-1.12.2-1.2.5.10_1.jar                     | b1GV9Jm2u7rmsCe65wKzPTw5jtS38n2tVEGi45a1 |
	| LC    | cosmeticarmorreworked                        | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | craftstudioapi                               | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar            | None                                     |
	| LC    | dailies                                      | 1.12.2-6                 | dailies-1.12.2-6_1.jar                           | None                                     |
	| LC    | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar                  | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar              | None                                     |
	| LC    | cdm                                          | 0.4.1                    | device-mod-0.4.1-1.12.2.jar                      | None                                     |
	| LC    | dungeonsmod                                  | @VERSION@                | DungeonsMod-1.12.2-1.0.8.jar                     | None                                     |
	| LC    | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                            | None                                     |
	| LC    | forgelin                                     | 1.8.4                    | Forgelin-1.8.4_1.jar                             | None                                     |
	| LC    | lizardfurnituremod                           | 1.1.0                    | FurbishCraft1.2.11.12.2.jar                      | None                                     |
	| LC    | cfm                                          | 6.3.1                    | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LC    | ironman                                      | Beta-1.12.2-1.2.6        | IronMan-1.12.2-Beta-1.12.2-1.2.6.jar             | None                                     |
	| LC    | lucraftcore                                  | 1.12.2-2.4.16            | LucraftCore-1.12.2-2.4.16_1.jar                  | None                                     |
	| LC    | heroesexpansion                              | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5_1.jar               | None                                     |
	| LC    | waila                                        | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LC    | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                                    | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LC    | journeymap                                   | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                      | None                                     |
	| LC    | mekanism                                     | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390_1.jar                  | None                                     |
	| LC    | mekanismgenerators                           | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390_1.jar        | None                                     |
	| LC    | mekanismtools                                | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390_1.jar             | None                                     |
	| LC    | morpheus                                     | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                      | None                                     |
	| LC    | llibrary                                     | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | mowziesmobs                                  | 1.5.8                    | mowziesmobs-1.5.8.jar                            | None                                     |
	| LC    | overpoweredarmorbar                          | @VERSION@                | overloadedarmorbar-1.0.4g.jar                    | None                                     |
	| LC    | harvestcraft                                 | 1.12.2zb                 | PamsHarvestCraft1.12.2zg_1.jar                   | None                                     |
	| LC    | patchouli                                    | 1.0-23.6                 | Patchouli-1.0-23.6_1.jar                         | None                                     |
	| LC    | placeableitems                               | 3.3                      | placeableitems-3.3_1.jar                         | None                                     |
	| LC    | railcraft                                    | 12.0.0                   | railcraft-12.0.0_1.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | reccomplex                                   | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                     | None                                     |
	| LC    | stg                                          | 1.12.2-1.2.3             | stg-1.12.2-1.2.3_1.jar                           | None                                     |
	| LC    | storagedrawers                               | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                  | None                                     |
	| LC    | tektopia                                     | 1.1.0                    | tektopia-1.1.0.jar                               | None                                     |
	| LC    | thermalfoundation                            | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal_1.jar | None                                     |
	| LC    | thermalexpansion                             | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal_1.jar  | None                                     |
	| LC    | travelersbackpack                            | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35_1.jar            | None                                     |
	| LC    | waystones                                    | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16_1.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
ForgelinPlugin (Forgelin-1.8.4_1.jar)
  
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31_1.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390_1.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14742 Compatibility Profile Context 21.8.1 27.20.22023.1004' Renderer: 'AMD Radeon RX 6700 XT'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14742 Compatibility Profile Context 21.8.1 27.20.22023.1004
	OpenGlRenderer: AMD Radeon RX 6700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by covers1624** [comment] 2021-11-18 09:16
Please look at existing issues before opening new ones.

Duplicate of: https://github.com/TheCBProject/CodeChickenLib/issues/270

**Closed as completed by covers1624** 2021-11-18 09:16 UTC
