### ISSUE TITLE
why does this keep happening

### ISSUE THREAD

**Issue by hazbin95mannco** [TheCBProject/CodeChickenLib#371] opened 2021-09-06 22:21 UTC
WARNING: coremods are present:
  LogisticsPipesCoreLoader (logisticspipes-0.10.3.114.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/6/21 3:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 474095448 bytes (452 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                        | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | securitycraft       | v1.8.23.2         | [1.12.2]+SecurityCraft+v1.8.23.2.jar          | None                                     |
	| LCH   | buildcraftlib       | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | additionalpipes     | 6.0.0.8           | additionalpipes-6.0.0.8.jar                   | None                                     |
	| LCH   | bno                 | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar            | None                                     |
	| LCH   | bibliocraft         | 2.4.5             | BiblioCraft-1.12.2.jar                        | None                                     |
	| LCH   | bluepower           | 0.3.152           | BluePower-1.12.2-0.3.152-universal.jar        | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | ic2                 | 2.8.1001          | IC2Classic+1.12-1.5.5.2.1.jar                 | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCE   | codechickenlib      | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chickenchunks       | 2.4.2.74          | ChickenChunks-1.12.2-2.4.2.74-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux        | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
	| LC    | cofhcore            | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar         | None                                     |
	| LC    | cyberware           | 0.2.10.15         | cyberware-1.12.2-0.2.10.15.jar                | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LC    | energyconverters    | 1.3.7.30          | energyconverters_1.12.2-1.3.7.30.jar          | None                                     |
	| LC    | ic2-classic-spmod   | 0.0.0.0           | IC2Classic+1.12-1.5.5.2.1.jar                 | None                                     |
	| LC    | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LC    | jei                 | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | jeiintegration      | 1.6.0             | jeiintegration_1.12.2-1.6.0.jar               | None                                     |
	| LC    | logisticspipes      | 0.10.3.114        | logisticspipes-0.10.3.114.jar                 | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
	| LC    | mapwriter           | 2.8.2             | MapWriter-1.12.2-2.8.2.jar                    | None                                     |
	| LC    | mousetweaks         | 2.10.1            | MouseTweaks-2.10.1-mc1.12.2.jar               | None                                     |
	| LC    | nei                 | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | numina              | 1.12.2-1.0.38     | Numina-1.12.2-1.0.38.jar                      | None                                     |
	| LC    | projecte            | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| LC    | redstonearsenal     | 2.6.6             | RedstoneArsenal-1.12.2-2.6.6.1-universal.jar  | None                                     |
	| LC    | solarflux           | 4.35r             | SolarFluxReborn_1.12.2-4.35r.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | zettaindustries     | 1.3               | zettaindustries-1.3-1.12.2-161.jar            | None                                     |

**Comment by covers1624** [comment] 2021-09-07 08:47
Please look for existing issues before opening a new one.

Duplicate of https://github.com/TheCBProject/CodeChickenLib/issues/270

**Closed as completed by covers1624** 2021-09-07 08:47 UTC
