### ISSUE TITLE
(codechickenlib) error

### ISSUE THREAD

**Issue by plopezh9** [TheCBProject/CodeChickenLib#335] opened 2021-01-19 00:57 UTC
hola tengo un error que no eh podido resolver  ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1 (1).jar)
  LoadingPlugin (CrashToMainMenu-client-1.12.2-1.0.0 (1).jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 1/18/21 9:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.wildbamaboy.crashtomainmenu.asm.ASMHooks.onMinecraftRun(ASMHooks.java:37)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3504563184 bytes (3342 MB) / 5368709120 bytes (5120 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2852 Optifine OptiFine_1.12.2_HD_U_F5 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version               | Source                                            | Signature                                |
	|:----- |:------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCH   | mcp                 | 9.42                  | minecraft.jar                                     | None                                     |
	| LCH   | FML                 | 8.0.99.99             | forge-1.12.2-14.23.5.2852.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2852          | forge-1.12.2-14.23.5.2852.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                       | minecraft.jar                                     | None                                     |
	| LCH   | aether_legacy       | 1.4.4                 | Aether-Legacy-Mod-1.12.2.jar                      | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55 (1).jar                      | None                                     |
	| LCH   | jei                 | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCH   | twilightforest      | 3.11.1021             | twilightforest-1.12.2-3.11.1021-universal.jar     | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.13.0.171     | TConstruct-1.12.2-2.13.0.171.jar                  | None                                     |
	| LCH   | thedragonlib        | 1.12.2-5.3.0          | thedragonlib-1.12.2-5.3.0.jar                     | None                                     |
	| LCH   | armorplus           | 1.12.2-11.28.0.69     | armorplus-1.12.2-11.28.0.69.jar                   | None                                     |
	| LCH   | bibliocraft         | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCH   | bibliotheca         | 1.3.6-1.12.2          | bibliotheca-1.3.6-1.12.2.jar                      | None                                     |
	| LCH   | biomesoplenty       | 7.0.1.2441            | BiomesOPlenty-1.12.2-7.0.1.2441-universal (2).jar | None                                     |
	| LCH   | bookshelf           | 2.3.557               | Bookshelf-1.12.2-2.3.557 (1).jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | buildcraftlib       | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftcore      | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftbuilders  | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcrafttransport | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftsilicon   | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | crafttweaker        | 4.1.20                | CraftTweaker2-1.12-4.1.20.586.jar                 | None                                     |
	| LCH   | ic2                 | 2.8.221-ex112         | industrialcraft-2-2.8.221-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | buildcraftcompat    | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.7             | buildcraft-all-7.99.24.7.jar                      | None                                     |
	| LCH   | chameleon           | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCH   | chesttransporter    | 2.8.8                 | ChestTransporter-1.12.2-2.8.8.jar                 | None                                     |
	| LCE   | codechickenlib      | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | ctgui               | 1.0.0                 | CraftTweaker2-1.12-4.1.20.586.jar                 | None                                     |
	| LC    | crafttweakerjei     | 2.0.3                 | CraftTweaker2-1.12-4.1.20.586.jar                 | None                                     |
	| LC    | customspawner       | 3.11.4                | CustomMobSpawner-3.11.5.jar                       | None                                     |
	| LC    | ptrmodellib         | 1.0.4                 | PTRLib-1.0.4.jar                                  | None                                     |
	| LC    | props               | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                        | None                                     |
	| LC    | elementalcreepers   | v4.3.3.g5616356       | Elemental-Creepers-Redux-Mod-1.12.2.jar           | None                                     |
	| LC    | eplus               | 5.0.176               | EnchantingPlus-1.12.2-5.0.176 (1).jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | enhancedfarming     | 1.1.3                 | Enhanced-Farming-1.12.2-1.1.3.jar                 | None                                     |
	| LC    | extrautils2         | 1.0                   | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LC    | fairylights         | 2.1.8                 | fairylights-2.1.8-1.12.2.jar                      | None                                     |
	| LC    | cfm                 | 6.3.1                 | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LC    | galacticraftcore    | 4.0.2.281             | GalacticraftCore-1.12.2-4.0.2.281.jar             | None                                     |
	| LC    | galacticraftplanets | 4.0.2.281             | Galacticraft-Planets-1.12.2-4.0.2.281.jar         | None                                     |
	| LC    | hammertime          | 2.2.0                 | Hammer+Time-2.2.0-1.12.2.jar                      | None                                     |
	| LC    | ichunutil           | 7.2.1                 | iChunUtil-1.12.2-7.2.1 (1).jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | ironchest           | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847 (1).jar               | None                                     |
	| LC    | journeymap          | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1 (1).jar                   | None                                     |
	| LC    | malisiscore         | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1 (1).jar                  | None                                     |
	| LC    | malisisdoors        | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0 (1).jar                 | None                                     |
	| LC    | mca                 | 6.1.0                 | MCA-1.12.2-6.1.0-universal (2).jar                | None                                     |
	| LC    | mocreatures         | 12.0.5                | Mo-Creatures-Mod-1.12.2.jar                       | None                                     |
	| LC    | morph               | 7.2.0                 | Morph-1.12.2-7.2.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | recipehandler       | 0.13                  | NoMoreRecipeConflict-0.13(1.12.2).jar             | None                                     |
	| LC    | nei                 | 2.4.3                 | NotEnoughItems-1.12.2-2.4.3.245-universal (1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | harvestcraft        | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zg.jar                   | None                                     |
	| LC    | recipes_and_more    | 1.0.1                 | RecipesAndMore-1.12.2-1.0.1.jar                   | None                                     |
	| LC    | redstonepaste       | 1.7.5                 | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
	| LC    | roguelike           | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| LC    | storagedrawers      | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar                   | None                                     |
	| LC    | travelersbackpack   | 1.0.34                | TravelersBackpack-1.12.2-1.0.34.jar               | None                                     |
	| LC    | tropicraft          | 7.1.9.115             | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
	| LC    | uncraftingtable     | 1.8-beta6             | Uncrafting-Table-Mod-1.12.2 (1).jar               | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1 (1).jar)
  
LoadingPlugin (CrashToMainMenu-client-1.12.2-1.0.0 (1).jar)
  com.wildbamaboy.crashtomainmenu.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 25
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.27 Medium.zip
	OpenGlVersion: 4.3.0 - Build 20.19.15.5126
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by covers1624** [comment] 2021-01-19 08:30
Duplicate of #270 

Please look at the existing open issues before opening a new one.

**Closed as completed by covers1624** 2021-01-19 08:30 UTC
