### ISSUE TITLE
[1.12.2] Crash on init game

### ISSUE THREAD

**Issue by KorDum** [TheCBProject/CodeChickenLib#153] opened 2018-06-12 17:03 UTC
https://paste.dimdev.org/edafazapew.mccrash
Java 8 r162 or latest r172

**Comment by covers1624** [comment] 2018-06-12 18:06
The launcher you are using is not using the correct version of LWJGL. Duplicate of https://github.com/TheCBProject/CodeChickenLib/issues/152

**Closed as completed by covers1624** 2018-06-12 18:06 UTC
