### ISSUE TITLE
it crashes on stratup

### ISSUE THREAD

**Issue by ghost** [TheCBProject/CodeChickenLib#377] opened 2021-11-01 21:48 UTC
This is the crash report with optifine:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  pymtech (PymTech-1.12.2-1.0.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 11/1/21 4:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 718759064 bytes (685 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version           | Source                                                | Signature                                |
	|:----- |:--------------- |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCH   | mcp             | 9.42              | minecraft.jar                                         | None                                     |
	| LCH   | FML             | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate       | 0.4.2             | minecraft.jar                                         | None                                     |
	| LCH   | ageofweapons    | 0.13.5            | Age+of+Weapons+1.12.2++(v.0.13.5).jar                 | None                                     |
	| LCE   | codechickenlib  | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia        | 3.3.0             | Avaritia-1.12.2-3.3.0.37-universal.jar                | None                                     |
	| LC    | gorecore        | 1.12.2-0.4.5      | avatarmod-1.5.17-alpha.jar                            | None                                     |
	| LC    | avatarmod       | 1.5.17-alpha      | avatarmod-1.5.17-alpha.jar                            | None                                     |
	| LC    | blockarmor      | 2.4.12            | BlockArmor-1.12.2-2.4.12.jar                          | None                                     |
	| LC    | bookshelf       | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | mantle          | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LC    | jei             | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LC    | tconstruct      | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LC    | conarm          | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                            | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LC    | ebwizardry      | 4.3.4             | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| LC    | fm              | 1.8               | FunMod+1.9.jar                                        | None                                     |
	| LC    | cgm             | 0.15.3            | guns-0.15.3-1.12.2.jar                                | None                                     |
	| LC    | heroesarrival   | 1.0.0             | Heroes+Arrival+1.2.1.jar                              | None                                     |
	| LC    | speedsterheroes | 1.12.2-2.2.1      | SpeedsterHeroes-1.12.2-2.2.1.jar                      | None                                     |
	| LC    | lucraftcore     | 1.12.2-2.4.16     | LucraftCore-1.12.2-2.4.16.jar                         | None                                     |
	| LC    | heroesexpansion | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar                      | None                                     |
	| LC    | msmlegacy       | @VERSION@         | MoreSwordsLegacy-1.12.2-1.0.7.jar                     | None                                     |
	| LC    | mo_swords       | v5                | moSwords-1.12.2v5.jar                                 | None                                     |
	| LC    | mam             | 1.0               | MystAdditions-1.0.jar                                 | None                                     |
	| LC    | pymtech         | 1.12.2-1.0.2      | PymTech-1.12.2-1.0.2.jar                              | None                                     |
	| LC    | spartanweaponry | beta 1.3.8        | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	| LC    | switchbow       | 1.6               | switchbow-1.6.jar                                     | None                                     |
	| LC    | the-fifth-world | 0.5               | the-fifth-world-0.5.1.jar                             | None                                     |
	| LC    | useless_sword   | 1.0.9             | UselessSword-1.12.2-V1.0.8.jar                        | None                                     |
	| LC    | vampirism       | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                            | None                                     |
	| LC    | teamlapen-lib   | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                            | None                                     |
	| LC    | worldedit       | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1).jar | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
pymtech (PymTech-1.12.2-1.0.2.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 2000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics 2000
	OpenGlVendor: Intel
	CpuCount: 4
This is without optifine:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  pymtech (PymTech-1.12.2-1.0.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 11/1/21 4:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 585215488 bytes (558 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version           | Source                                                | Signature                                |
	|:----- |:--------------- |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCH   | mcp             | 9.42              | minecraft.jar                                         | None                                     |
	| LCH   | FML             | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate       | 0.4.2             | minecraft.jar                                         | None                                     |
	| LCH   | ageofweapons    | 0.13.5            | Age+of+Weapons+1.12.2++(v.0.13.5).jar                 | None                                     |
	| LCE   | codechickenlib  | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | avaritia        | 3.3.0             | Avaritia-1.12.2-3.3.0.37-universal.jar                | None                                     |
	| LC    | gorecore        | 1.12.2-0.4.5      | avatarmod-1.5.17-alpha.jar                            | None                                     |
	| LC    | avatarmod       | 1.5.17-alpha      | avatarmod-1.5.17-alpha.jar                            | None                                     |
	| LC    | blockarmor      | 2.4.12            | BlockArmor-1.12.2-2.4.12.jar                          | None                                     |
	| LC    | bookshelf       | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | mantle          | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                              | None                                     |
	| LC    | jei             | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LC    | tconstruct      | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                      | None                                     |
	| LC    | conarm          | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                            | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LC    | ebwizardry      | 4.3.4             | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| LC    | fm              | 1.8               | FunMod+1.9.jar                                        | None                                     |
	| LC    | cgm             | 0.15.3            | guns-0.15.3-1.12.2.jar                                | None                                     |
	| LC    | heroesarrival   | 1.0.0             | Heroes+Arrival+1.2.1.jar                              | None                                     |
	| LC    | speedsterheroes | 1.12.2-2.2.1      | SpeedsterHeroes-1.12.2-2.2.1.jar                      | None                                     |
	| LC    | lucraftcore     | 1.12.2-2.4.16     | LucraftCore-1.12.2-2.4.16.jar                         | None                                     |
	| LC    | heroesexpansion | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar                      | None                                     |
	| LC    | msmlegacy       | @VERSION@         | MoreSwordsLegacy-1.12.2-1.0.7.jar                     | None                                     |
	| LC    | mo_swords       | v5                | moSwords-1.12.2v5.jar                                 | None                                     |
	| LC    | mam             | 1.0               | MystAdditions-1.0.jar                                 | None                                     |
	| LC    | pymtech         | 1.12.2-1.0.2      | PymTech-1.12.2-1.0.2.jar                              | None                                     |
	| LC    | spartanweaponry | beta 1.3.8        | SpartanWeaponry-1.12.2-beta-1.3.8.jar                 | None                                     |
	| LC    | switchbow       | 1.6               | switchbow-1.6.jar                                     | None                                     |
	| LC    | the-fifth-world | 0.5               | the-fifth-world-0.5.1.jar                             | None                                     |
	| LC    | useless_sword   | 1.0.9             | UselessSword-1.12.2-V1.0.8.jar                        | None                                     |
	| LC    | vampirism       | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                            | None                                     |
	| LC    | teamlapen-lib   | 1.6.2             | Vampirism-1.12.2-1.6.2.jar                            | None                                     |
	| LC    | worldedit       | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1).jar | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
pymtech (PymTech-1.12.2-1.0.2.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 2000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

**Comment by covers1624** [comment] 2021-11-05 09:52
Duplicate of: https://github.com/TheCBProject/CodeChickenLib/issues/270

**Closed as completed by covers1624** 2021-11-05 09:52 UTC
