### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by FedericoG121** [TheCBProject/CodeChickenLib#329] opened 2020-12-22 18:39 UTC
Crash report [crash-2020-12-22_19.31.46-client.txt](https://github.com/TheCBProject/CodeChickenLib/files/5731475/crash-2020-12-22_19.31.46-client.txt)

**Comment by covers1624** [comment] 2020-12-23 00:47
Duplicate of #270

**Closed as completed by covers1624** 2020-12-23 00:47 UTC
