### ISSUE TITLE
3 line error message every time a player joins server

### ISSUE THREAD

**Issue by khazoda** [TheCBProject/CodeChickenLib#331] opened 2020-12-25 16:32 UTC
On player joining server with both client and server using CodeChickenLib, ChickenChunks and EnderStorage, the following error message is printed to the server console 3 times, with the EntityTypeArgument number changing each time:

Could not serialize codechicken.lib.internal.command.EntityTypeArgument@633519f (class codechicken.lib.internal.command.EntityTypeArgument) - will not be sent to client!

Versions
======
CodeChickenLib-1.16.4-3.5.0.398-universal
EnderStorage-1.16.4-2.7.0.159-universal
ChickenChunks-1.16.4-2.7.0.85-universal

forge-1.16.4-35.1.13

**Comment by covers1624** [comment] 2020-12-26 13:56
Duplicate of: https://github.com/TheCBProject/CodeChickenLib/issues/325

**Closed as completed by covers1624** 2020-12-26 13:56 UTC
